- name: app
  type: "java:11"
  disk: 1024
  hooks:
    build: ./mvnw package
  relationships:
    database: "db:postgresql"
  web:
    commands:
      start: java -jar $JAVA_OPTS target/jpa-angular-1.0-SNAPSHOT-runner.jar